services:
  app:
    build: .
    container_name: php-multi-app
    ports:
      - "80:80"
      - "3306:3306"
      - "27017:27017"
      - "6379:6379"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./www:/var/www/html
      # 添加PHP配置目录挂载，方便修改配置
      - ./php7.4:/etc/php/7.4
      - ./php8.0:/etc/php/8.0
      - ./php8.2:/etc/php/8.2
      - ./php8.3:/etc/php/8.3
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=userpassword
      - REDIS_PASSWORD=your_redis_password
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge