services:
  app:
    image: tingrays:debian-bookworm
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php-multi-app
    cap_add:
      - SYS_RESOURCE
      - SYS_NICE
    ports:
      - "80:80"
      - "3306:3306"
      - "27017:27017"
      - "6379:6379"
    volumes:
      # Nginx
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www/:/var/www/html/
      # Mysql
      # Mysql配置
      - ./mysql/conf/my.cnf:/etc/alternatives/my.cnf
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf/my.cnf.fallback:/etc/mysql/my.cnf.fallback
      - ./mysql/conf/mysql.cnf:/etc/mysql/mysql.cnf
      - ./mysql/conf/conf.d/:/etc/mysql/conf.d/
      - ./mysql/conf/mysql.conf.d/:/etc/mysql/mysql.conf.d/
      # Mysql数据
      # - ./mysql/data/:/var/lib/mysql/
      # Redis
      - ./redis/:/etc/redis/
      # Mongodb
      # - ./mongodb/data/:/var/lib/mongodb/
      - ./mongodb/log/:/var/log/mongodb/
      - ./mongodb/mongod.conf:/etc/mongod.conf
      # PHP配置目录挂载
      # PHP7.4
      - ./php/7.4/cli/php.ini:/etc/php/7.4/cli/php.ini
      - ./php/7.4/fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./php/7.4/fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./php/7.4/fpm/pool.d:/etc/php/7.4/fpm/pool.d
      - ./php/7.4/mods-available/:/etc/php/7.4/mods-available/
      # PHP8.0
      - ./php/8.0/cli/php.ini:/etc/php/8.0/cli/php.ini
      - ./php/8.0/fpm/php-fpm.conf:/etc/php/8.0/fpm/php-fpm.conf
      - ./php/8.0/fpm/php.ini:/etc/php/8.0/fpm/php.ini
      - ./php/8.0/fpm/pool.d:/etc/php/8.0/fpm/pool.d
      - ./php/8.0/mods-available/:/etc/php/8.0/mods-available/
      # PHP8.0
      - ./php/8.3/cli/php.ini:/etc/php/8.3/cli/php.ini
      - ./php/8.3/fpm/php-fpm.conf:/etc/php/8.3/fpm/php-fpm.conf
      - ./php/8.3/fpm/php.ini:/etc/php/8.3/fpm/php.ini
      - ./php/8.3/fpm/pool.d:/etc/php/8.3/fpm/pool.d
      - ./php/8.3/mods-available/:/etc/php/8.3/mods-available/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge