# server {
#     listen       80;
#     server_name  localhost;

#     #access_log  /var/log/nginx/host.access.log  main;

#     location / {
#         root   /usr/share/nginx/html;
#         index  index.html index.htm;
#     }

#     #error_page  404              /404.html;

#     # redirect server error pages to the static page /50x.html
#     #
#     error_page   500 502 503 504  /50x.html;
#     location = /50x.html {
#         root   /usr/share/nginx/html;
#     }

#     # proxy the PHP scripts to Apache listening on 127.0.0.1:80
#     #
#     #location ~ \.php$ {
#     #    proxy_pass   http://127.0.0.1;
#     #}

#     # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
#     #
#     #location ~ \.php$ {
#     #    root           html;
#     #    fastcgi_pass   127.0.0.1:9000;
#     #    fastcgi_index  index.php;
#     #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
#     #    include        fastcgi_params;
#     #}

#     # deny access to .htaccess files, if Apache's document root
#     # concurs with nginx's one
#     #
#     #location ~ /\.ht {
#     #    deny  all;
#     #}
# }
server {
    listen 80;
	listen 443 ssl;
	server_name txy.dev.57ku.com;
    index index.html index.htm index.php;
    root /var/www/html/txy.57ku/web/public;

    autoindex off;

    #301_START
    #301_END

    #HTTP_TO_HTTPS_START
    if ($scheme != https){
        return 301 https://$host$request_uri;
    }
	#HTTP_TO_HTTPS_END

    #SSL_START
    ssl_certificate /var/www/html/SSL/txy_dev_57ku.crt;
    ssl_certificate_key /var/www/html/SSL/txy_dev_57ku.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
	#SSL_END


    #REWRITE_START 引用url重写规则
    location / {
        if (!-e $request_filename){
            rewrite  ^(.*)$  /index.php?s=$1  last;   break;
        }
    }
    #REWRITE_END

    #PHP_START
	location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_intercept_errors on;
    }
	#PHP_END

    #PHPMYADMIN_START
    #PHPMYADMIN_END

    #DENY_FILES_START
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 403;
    }
    #DENY_FILES_END

    location ~ .+\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      1d;
        error_log nul;
        access_log off;
    }

    location ~ .+\.(js|css)$
    {
        expires      1h;
        error_log nul;
        access_log off;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    access_log /var/log/nginx/txy.dev.57ku.com.access.log;
    error_log /var/log/nginx/txy.dev.57ku.com.error.log;
}
