version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
      - "3306:3306"
      - "6379:6379"
    volumes:
      - ./www:/var/www/html
      - ./mysql-data:/var/lib/mysql
      - ./redis-data:/var/lib/redis
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
